### ISSUE TITLE
Noob question -- tried to selfhost.

### ISSUE THREAD

**Issue by unpredictable** [Pomfe/pomfe.co#16]
I've got a domain that I wanted to host files on.

I'm using PHPMyAdmin and CPanel, but I'm getting a server error when uploading files. How can I fix this?

`define('POMF_DB_CONN', 'mysql:host=localhost;port=3306;dbname=domain_pomf');` 
`define('POMF_FILES_ROOT', '/public_html/a/files/');`

**Comment by VottonDev** [comment]
You should check your web server error logs and provide the detailed log.

**Comment by ghost** [comment]
..........

**Comment by ZythVX** [comment]
Go to /public_html/a/files
Create a file called test.php
Open test.php in an editor and paste this in:
`<?= getcwd(); ?>`
Then open the file in your browser (yourdomain.tld/a/files/test.php) and paste the text that it displays

**Comment by ghost** [comment]
..........

**Comment by ZythVX** [comment]
Try replace
`define('POMF_FILES_ROOT', '/public_html/a/files/');`
with
`define('POMF_FILES_ROOT', '/home/account/public_html/a/files/');`

**Comment by ghost** [comment]
..........

**Comment by ZythVX** [comment]
No problem :)
