### ISSUE TITLE
User Panel

### ISSUE THREAD

**Issue by VottonDev** [Pomfe/pomfe.co#4]
Might work on a User Panel at some point so the users are able to register and login.
The user panel lets you delete the files you have uploaded or you are able to see the files you have uploaded in the past if you don't have any Browser History for example.

**Comment by RithariDev** [comment]
With some clever design you can pull this off, I am against registration though as that would be a contradiction to the being 100% anonymous policy for the users. Just keep a history that works based on browser data. No file deletion, if someone wants an upload to be taken down, they shall fill out a complaint. 
+Support for the viewing part.

**Comment by VottonDev** [comment]
The passwords would be hashed and salted so user details would be safe, Also i would implement a Privacy Policy for this purpose as well. Anyways will see about this stuff anyways.

**Comment by ZythVX** [comment]
In the works
